# This is a basic workflow to help you get started with Actions

name: Build


# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.0
          haxelib --never install flixel 5.3.1
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel-addons 3.1.1 --quiet
          haxelib install tjson --quiet
          haxelib install hxCodec --quiet
          haxelib git luajit https://github.com/nebulazorua/linc_luajit --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib list

      - name: Compile
        run: haxelib run lime build linux -release

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: html5Build
          path: 'export/release/linux/bin'
  buildWindows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.0
          haxelib --never install flixel 5.3.1
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel-addons 3.1.1 --quiet
          haxelib install tjson --quiet
          haxelib install hxCodec --quiet
          haxelib git luajit https://github.com/nebulazorua/linc_luajit --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib list

      - name: Compile
        run: haxelib run lime build windows -release

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: LinuxBuild
          path: 'export/release/linux/bin'
  buildMac:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.0
          haxelib --never install flixel 5.3.1
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel-addons 3.1.1 --quiet
          haxelib install tjson --quiet
          haxelib install hxCodec --quiet
          haxelib git luajit https://github.com/nebulazorua/linc_luajit --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib list

      - name: Compile
        run: haxelib run lime build mac -release

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: html5Build
          path: 'export/release/mac/bin'

